"""add cascade delete to price history

Revision ID: 2eb7804d16ba
Revises: 20e769a20e6e
Create Date: 2026-02-24 20:26:35.205431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eb7804d16ba'
down_revision: Union[str, Sequence[str], None] = '20e769a20e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('prices_product_id_fkey'), 'prices', type_='foreignkey')
    op.create_foreign_key(None, 'prices', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prices', type_='foreignkey')
    op.create_foreign_key(op.f('prices_product_id_fkey'), 'prices', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
